apiVersion: v1
kind: Service
metadata:
  name: hello-kubernetes
  namespace: default
  labels:
    app: hello-kubernetes
spec:
  selector:
    app: hello-kubernetes
  ports:
    - protocol: TCP
      port: 80
      targetPort: http
      nodePort: 32033
  type: NodePort
